"""store recording audio in db

Revision ID: 3b216972e860
Revises: 9b9d6288fa1a
Create Date: 2026-07-19 21:00:26.504836

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3b216972e860'
down_revision: Union[str, None] = '9b9d6288fa1a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Existing rows point at files under the old upload_dir, which this schema
    # no longer references — their audio can't be carried into the row without
    # the migration reading the local filesystem, which won't exist on a fresh
    # deploy. Drop them rather than fabricate empty audio; on a new database
    # this is a no-op.
    op.execute('DELETE FROM vocal_recordings')
    op.add_column('vocal_recordings', sa.Column('audio_data', sa.LargeBinary(), nullable=False))
    op.drop_column('vocal_recordings', 'filename')


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vocal_recordings', sa.Column('filename', sa.VARCHAR(length=255), nullable=False))
    op.drop_column('vocal_recordings', 'audio_data')
    # ### end Alembic commands ###
