"""add economy, achievements, collab, company, online systems

Revision ID: 905e5ce93cf4
Revises: d12e916645cb
Create Date: 2026-07-18 20:35:16.285599

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '905e5ce93cf4'
down_revision: Union[str, None] = 'd12e916645cb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('character_achievements',
    sa.Column('character_id', sa.String(length=36), nullable=False),
    sa.Column('achievement_id', sa.String(length=50), nullable=False),
    sa.Column('unlocked_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], ),
    sa.PrimaryKeyConstraint('character_id', 'achievement_id')
    )
    op.create_table('companies',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('owner_character_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('capital', sa.Numeric(), nullable=False),
    sa.Column('founded_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['owner_character_id'], ['characters.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('owner_character_id')
    )
    op.create_table('concerts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('host_character_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('venue_capacity', sa.Integer(), nullable=False),
    sa.Column('ticket_price', sa.Numeric(), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['host_character_id'], ['characters.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_concerts_host_character_id'), 'concerts', ['host_character_id'], unique=False)
    op.create_table('collab_invites',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('song_id', sa.String(length=36), nullable=False),
    sa.Column('inviter_character_id', sa.String(length=36), nullable=False),
    sa.Column('invitee_character_id', sa.String(length=36), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('contribution_pct', sa.Numeric(), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['invitee_character_id'], ['characters.id'], ),
    sa.ForeignKeyConstraint(['inviter_character_id'], ['characters.id'], ),
    sa.ForeignKeyConstraint(['song_id'], ['songs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_collab_invites_invitee_character_id'), 'collab_invites', ['invitee_character_id'], unique=False)
    op.create_index(op.f('ix_collab_invites_song_id'), 'collab_invites', ['song_id'], unique=False)
    op.create_table('concert_tickets',
    sa.Column('concert_id', sa.String(length=36), nullable=False),
    sa.Column('character_id', sa.String(length=36), nullable=False),
    sa.Column('purchased_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], ),
    sa.ForeignKeyConstraint(['concert_id'], ['concerts.id'], ),
    sa.PrimaryKeyConstraint('concert_id', 'character_id')
    )
    op.create_table('groups',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('company_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('fame', sa.Numeric(), nullable=False),
    sa.Column('fans_count', sa.Integer(), nullable=False),
    sa.Column('debuted_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_groups_company_id'), 'groups', ['company_id'], unique=False)
    op.create_table('marketplace_listings',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('song_id', sa.String(length=36), nullable=False),
    sa.Column('seller_character_id', sa.String(length=36), nullable=False),
    sa.Column('price', sa.Numeric(), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('buyer_character_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('sold_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['buyer_character_id'], ['characters.id'], ),
    sa.ForeignKeyConstraint(['seller_character_id'], ['characters.id'], ),
    sa.ForeignKeyConstraint(['song_id'], ['songs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_marketplace_listings_seller_character_id'), 'marketplace_listings', ['seller_character_id'], unique=False)
    op.create_index(op.f('ix_marketplace_listings_song_id'), 'marketplace_listings', ['song_id'], unique=False)
    op.create_table('song_collaborators',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('song_id', sa.String(length=36), nullable=False),
    sa.Column('character_id', sa.String(length=36), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('contribution_pct', sa.Numeric(), nullable=False),
    sa.Column('is_owner', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], ),
    sa.ForeignKeyConstraint(['song_id'], ['songs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_song_collaborators_character_id'), 'song_collaborators', ['character_id'], unique=False)
    op.create_index(op.f('ix_song_collaborators_song_id'), 'song_collaborators', ['song_id'], unique=False)
    op.create_table('trainees',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('company_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('stats', sa.JSON(), nullable=False),
    sa.Column('talent', sa.JSON(), nullable=False),
    sa.Column('curriculum_stage', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trainees_company_id'), 'trainees', ['company_id'], unique=False)
    # server_default so the non-nullable columns backfill cleanly on any
    # existing rows (Postgres prod); harmless on a fresh SQLite dev DB.
    op.add_column('characters', sa.Column('total_streams', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('characters', sa.Column('last_simulated_at', sa.DateTime(), nullable=False, server_default=sa.func.now()))
    op.add_column('songs', sa.Column('revenue_breakdown', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('songs', 'revenue_breakdown')
    op.drop_column('characters', 'last_simulated_at')
    op.drop_column('characters', 'total_streams')
    op.drop_index(op.f('ix_trainees_company_id'), table_name='trainees')
    op.drop_table('trainees')
    op.drop_index(op.f('ix_song_collaborators_song_id'), table_name='song_collaborators')
    op.drop_index(op.f('ix_song_collaborators_character_id'), table_name='song_collaborators')
    op.drop_table('song_collaborators')
    op.drop_index(op.f('ix_marketplace_listings_song_id'), table_name='marketplace_listings')
    op.drop_index(op.f('ix_marketplace_listings_seller_character_id'), table_name='marketplace_listings')
    op.drop_table('marketplace_listings')
    op.drop_index(op.f('ix_groups_company_id'), table_name='groups')
    op.drop_table('groups')
    op.drop_table('concert_tickets')
    op.drop_index(op.f('ix_collab_invites_song_id'), table_name='collab_invites')
    op.drop_index(op.f('ix_collab_invites_invitee_character_id'), table_name='collab_invites')
    op.drop_table('collab_invites')
    op.drop_index(op.f('ix_concerts_host_character_id'), table_name='concerts')
    op.drop_table('concerts')
    op.drop_table('companies')
    op.drop_table('character_achievements')
    # ### end Alembic commands ###
