"""add vocal_recordings

Revision ID: 9b9d6288fa1a
Revises: 905e5ce93cf4
Create Date: 2026-07-19 16:03:28.883990

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9b9d6288fa1a'
down_revision: Union[str, None] = '905e5ce93cf4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vocal_recordings',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('character_id', sa.String(length=36), nullable=False),
    sa.Column('song_id', sa.String(length=36), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('mime_type', sa.String(length=80), nullable=False),
    sa.Column('duration_sec', sa.Numeric(), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], ),
    sa.ForeignKeyConstraint(['song_id'], ['songs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vocal_recordings_character_id'), 'vocal_recordings', ['character_id'], unique=False)
    op.create_index(op.f('ix_vocal_recordings_song_id'), 'vocal_recordings', ['song_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vocal_recordings_song_id'), table_name='vocal_recordings')
    op.drop_index(op.f('ix_vocal_recordings_character_id'), table_name='vocal_recordings')
    op.drop_table('vocal_recordings')
    # ### end Alembic commands ###
