"""in-game calendar: game_date, age, seasons

Revision ID: afe596b813f2
Revises: 3b216972e860
Create Date: 2026-07-19 21:47:05.077584

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'afe596b813f2'
down_revision: Union[str, None] = '3b216972e860'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('season_records',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('character_id', sa.String(length=36), nullable=False),
    sa.Column('season_index', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=20), nullable=False),
    sa.Column('ended_on', sa.Date(), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('fame', sa.Numeric(), nullable=False),
    sa.Column('money', sa.Numeric(), nullable=False),
    sa.Column('fans_count', sa.Integer(), nullable=False),
    sa.Column('total_streams', sa.Integer(), nullable=False),
    sa.Column('releases_this_season', sa.Integer(), nullable=False),
    sa.Column('best_song', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_season_records_character_id'), 'season_records', ['character_id'], unique=False)
    # server_default backfills characters that predate the calendar: they all
    # start at the epoch, aged 22 (the default background's starting age).
    op.add_column('characters', sa.Column('game_date', sa.Date(), nullable=False, server_default='2026-01-01'))
    op.add_column('characters', sa.Column('birth_date', sa.Date(), nullable=False, server_default='2004-01-01'))
    op.add_column('characters', sa.Column('last_settled_week', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('characters', sa.Column('last_settled_season', sa.Integer(), nullable=False, server_default='0'))
    op.drop_column('characters', 'last_simulated_at')
    op.add_column('songs', sa.Column('released_on', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('songs', 'released_on')
    op.add_column('characters', sa.Column('last_simulated_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False))
    op.drop_column('characters', 'last_settled_season')
    op.drop_column('characters', 'last_settled_week')
    op.drop_column('characters', 'birth_date')
    op.drop_column('characters', 'game_date')
    op.drop_index(op.f('ix_season_records_character_id'), table_name='season_records')
    op.drop_table('season_records')
    # ### end Alembic commands ###
