"""initial schema

Revision ID: d12e916645cb
Revises: 
Create Date: 2026-07-18 16:53:40.524725

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd12e916645cb'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fan_personas',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('color', sa.String(length=10), nullable=True),
    sa.Column('genre_pref', sa.JSON(), nullable=False),
    sa.Column('mood_pref', sa.JSON(), nullable=False),
    sa.Column('openness', sa.Numeric(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('npc_artists',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('color', sa.String(length=10), nullable=True),
    sa.Column('genre', sa.String(length=40), nullable=True),
    sa.Column('bio', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('characters',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('artist_name', sa.String(length=120), nullable=False),
    sa.Column('background_id', sa.String(length=40), nullable=False),
    sa.Column('background_name', sa.String(length=120), nullable=False),
    sa.Column('stats', sa.JSON(), nullable=False),
    sa.Column('talent', sa.JSON(), nullable=False),
    sa.Column('fame', sa.Numeric(), nullable=False),
    sa.Column('money', sa.Numeric(), nullable=False),
    sa.Column('fans_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('npc_songs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('npc_artist_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('tier', sa.String(length=10), nullable=False),
    sa.Column('score', sa.Numeric(), nullable=False),
    sa.Column('bpm', sa.Integer(), nullable=False),
    sa.Column('pattern', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['npc_artist_id'], ['npc_artists.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('character_fan_loyalty',
    sa.Column('character_id', sa.String(length=36), nullable=False),
    sa.Column('persona_id', sa.Integer(), nullable=False),
    sa.Column('loyalty_score', sa.Numeric(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], ),
    sa.ForeignKeyConstraint(['persona_id'], ['fan_personas.id'], ),
    sa.PrimaryKeyConstraint('character_id', 'persona_id')
    )
    op.create_table('follows',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('follower_character_id', sa.String(length=36), nullable=False),
    sa.Column('followed_type', sa.String(length=10), nullable=False),
    sa.Column('followed_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['follower_character_id'], ['characters.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('follower_character_id', 'followed_type', 'followed_id')
    )
    op.create_table('songs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('character_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('bpm', sa.Integer(), nullable=False),
    sa.Column('genre_tags', sa.JSON(), nullable=False),
    sa.Column('mood_tags', sa.JSON(), nullable=False),
    sa.Column('chord_preset_id', sa.String(length=10), nullable=False),
    sa.Column('production_mode', sa.String(length=10), nullable=False),
    sa.Column('vocal_source', sa.String(length=10), nullable=False),
    sa.Column('structure', sa.JSON(), nullable=False),
    sa.Column('pattern', sa.JSON(), nullable=False),
    sa.Column('lyrics', sa.JSON(), nullable=True),
    sa.Column('craft', sa.Numeric(), nullable=True),
    sa.Column('originality', sa.Numeric(), nullable=True),
    sa.Column('accessibility', sa.Numeric(), nullable=True),
    sa.Column('experimental', sa.Numeric(), nullable=True),
    sa.Column('overall_score', sa.Numeric(), nullable=True),
    sa.Column('tier', sa.String(length=10), nullable=True),
    sa.Column('genius_event', sa.Boolean(), nullable=False),
    sa.Column('sleeper_hit', sa.Boolean(), nullable=False),
    sa.Column('fans_delta', sa.Integer(), nullable=True),
    sa.Column('money_delta', sa.Numeric(), nullable=True),
    sa.Column('fame_delta', sa.Numeric(), nullable=True),
    sa.Column('released_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_songs_character_id'), 'songs', ['character_id'], unique=False)
    op.create_table('song_comments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('song_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['song_id'], ['songs.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_song_comments_song_id'), 'song_comments', ['song_id'], unique=False)
    op.create_table('song_likes',
    sa.Column('song_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['song_id'], ['songs.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('song_id', 'user_id')
    )
    op.create_table('song_reactions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('song_id', sa.String(length=36), nullable=False),
    sa.Column('persona_id', sa.Integer(), nullable=False),
    sa.Column('reached', sa.Boolean(), nullable=False),
    sa.Column('affinity', sa.Numeric(), nullable=False),
    sa.Column('reaction_score', sa.Numeric(), nullable=False),
    sa.Column('comment_line', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['persona_id'], ['fan_personas.id'], ),
    sa.ForeignKeyConstraint(['song_id'], ['songs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_song_reactions_song_id'), 'song_reactions', ['song_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_song_reactions_song_id'), table_name='song_reactions')
    op.drop_table('song_reactions')
    op.drop_table('song_likes')
    op.drop_index(op.f('ix_song_comments_song_id'), table_name='song_comments')
    op.drop_table('song_comments')
    op.drop_index(op.f('ix_songs_character_id'), table_name='songs')
    op.drop_table('songs')
    op.drop_table('follows')
    op.drop_table('character_fan_loyalty')
    op.drop_table('npc_songs')
    op.drop_table('characters')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('npc_artists')
    op.drop_table('fan_personas')
    # ### end Alembic commands ###
